name: 'Map Repo'
description: 'Upload map packages to S3'
inputs:
  aws-s3-package-bucket:
    description: 'FortressOne AWS S3 package bucket URI'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-access-key:
    description: 'AWS access key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS-S3-PACKAGE-BUCKET: ${{ inputs.AWS-S3-PACKAGE-BUCKET }}
    AWS-SECRET-ACCESS-KEY: ${{ inputs.AWS-SECRET-ACCESS-KEY }}
    AWS-ACCESS-KEY: ${{ inputs.AWS-ACCESS-KEY }}
