name: Upload Files
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Package into packaged bsps and upload to S3
        uses: ./
        id: map-repo
        env:
          AWS_S3_PACKAGE_BUCKET: ${{ secrets.AWS_S3_PACKAGE_BUCKET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
