name: Upload Files
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package into packaged bsps and upload to S3
        uses: ./
        id: map-repo
        env:
          AWS-S3-PACKAGE-BUCKET: ${{ secrets.AWS_S3_PACKAGE_BUCKET }}
          AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-ACCESS-KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
